version: "2"
run:
  timeout: 10m
  allow-parallel-runners: true
  tests: true
linters:
  default: none
  enable:
    - copyloopvar
    - dupl
    - err113
    - errcheck
    - gochecknoglobals
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - godox
    - gosec
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - nolintlint
    - prealloc
    - revive
    - staticcheck
    - unconvert
    - unparam
    - unused
    - whitespace
  settings:
    gosec:
      excludes:
        - G602 # delete after fix: https://github.com/securego/gosec/issues/1250
    errcheck:
      check-type-assertions: true
      check-blank: true
    goconst:
      min-len: 2
      min-occurrences: 2
    gocritic:
      disabled-checks:
        - whyNoLint
        - hugeParam
        - unnecessaryBlock
        - sloppyReassign
      enabled-tags:
        - diagnostic
        - performance
        - style
        - experimental
    govet:
      disable:
        - fieldalignment
        - composites
      enable-all: true
    lll:
      line-length: 120
    misspell:
      locale: US
    nolintlint:
      require-explanation: true
    revive:
      rules:
        - name: var-naming
          disabled: true
    staticcheck:
      checks:
        - all
        - -ST1003
    unused:
      field-writes-are-uses: false
      exported-fields-are-used: false
      local-variables-are-used: false
      generated-is-used: false
    whitespace:
      multi-if: true
      multi-func: true
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - err113
        path: (.+)_test.go
      - path: (.+)\.go$
        text: G101
      - path: (.+)\.go$
        text: G404
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
